// scripts/fetch-7news.mjs
//
// Fetches the latest 7NEWS headlines and writes a typed snapshot to
//   src/data/externalNews.ts
//
// This snapshot is bundled with the site so headlines render instantly
// (and as a fallback when the live in-browser refresh is unavailable).
//
// Run manually:        npm run news
// Run daily (cron):    0 6 * * *  cd /path/to/bivry-landing && npm run news
// Or via GitHub Action / CI before each deploy — see README note.

import { writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// 7NEWS RSS feeds (business is the most relevant for a logistics brand).
// Swap to 'https://7news.com.au/news/feed' for general news.
const FEED_URL = 'https://7news.com.au/business/feed'
const MAX_ITEMS = 9
const OUT_FILE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'data',
  'externalNews.ts',
)

// rss2json converts the RSS XML into clean, CORS-friendly JSON.
const PROXY = `https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(FEED_URL)}`

const stripHtml = (s = '') =>
  s.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()

const firstImage = (item) => {
  if (item.thumbnail) return item.thumbnail
  if (item.enclosure && item.enclosure.link) return item.enclosure.link
  const m = (item.content || item.description || '').match(/<img[^>]+src="([^"]+)"/i)
  return m ? m[1] : ''
}

async function main() {
  console.log(`→ Fetching 7NEWS feed: ${FEED_URL}`)
  const res = await fetch(PROXY, { headers: { 'User-Agent': 'bivry-news-bot/1.0' } })
  if (!res.ok) throw new Error(`Feed request failed: ${res.status} ${res.statusText}`)

  const data = await res.json()
  if (data.status !== 'ok' || !Array.isArray(data.items)) {
    throw new Error(`Unexpected feed payload: ${data.message || data.status}`)
  }

  const items = data.items.slice(0, MAX_ITEMS).map((it) => ({
    title: stripHtml(it.title),
    link: it.link,
    pubDate: it.pubDate || '',
    excerpt: stripHtml(it.description).slice(0, 160),
    image: firstImage(it),
  }))

  const payload = {
    source: '7NEWS',
    sourceUrl: 'https://7news.com.au/',
    feed: FEED_URL,
    fetchedAt: new Date().toISOString(),
    items,
  }

  const file = `// AUTO-GENERATED by scripts/fetch-7news.mjs — do not edit by hand.
// Run \`npm run news\` to refresh. Source: ${FEED_URL}

export interface ExternalNewsItem {
  title: string
  link: string
  pubDate: string
  excerpt: string
  image: string
}

export interface ExternalNews {
  source: string
  sourceUrl: string
  feed: string
  fetchedAt: string
  items: ExternalNewsItem[]
}

export const externalNews: ExternalNews = ${JSON.stringify(payload, null, 2)}
`

  await mkdir(dirname(OUT_FILE), { recursive: true })
  await writeFile(OUT_FILE, file, 'utf8')
  console.log(`✓ Wrote ${items.length} headlines → ${OUT_FILE}`)
}

main().catch((err) => {
  console.error('✗ fetch-7news failed:', err.message)
  process.exit(1)
})
