// AUTO-GENERATED by scripts/fetch-7news.mjs — do not edit by hand.
// Run `npm run news` to refresh. Source: https://7news.com.au/business/feed

export interface ExternalNewsItem {
  title: string
  link: string
  pubDate: string
  excerpt: string
  image: string
}

export interface ExternalNews {
  source: string
  sourceUrl: string
  feed: string
  fetchedAt: string
  items: ExternalNewsItem[]
}

export const externalNews: ExternalNews = {
  "source": "7NEWS",
  "sourceUrl": "https://7news.com.au/",
  "feed": "https://7news.com.au/business/feed",
  "fetchedAt": "2026-06-16T08:31:01.474Z",
  "items": [
    {
      "title": "RBA interest rates: Reserve Bank holds cash rate at 4.35 per cent in relief for Australian borrowers",
      "link": "https://7news.com.au/news/rba-interest-rates-reserve-bank-holds-cash-rate-at-435-per-cent-in-relief-for-australia-borrowers--c-22439119",
      "pubDate": "2026-06-16 04:30:33",
      "excerpt": "A fourth consecutive rate hike would have turned the dial up to a level not seen in almost 15 years.",
      "image": ""
    },
    {
      "title": "Lincraft to close all physical stores in Australia and New Zealand as part of digital shift",
      "link": "https://7news.com.au/news/lincraft-to-close-all-physical-stores-in-australia-and-new-zealand-as-part-of-digital-shift-c-22438972",
      "pubDate": "2026-06-16 04:11:27",
      "excerpt": "Customers were informed of the major development in an email.",
      "image": "https://images.7news.com.au/publication/C-22438972/bd2de1061410f374fd2b34f6f812c535e288dcc1-16x9-x0y75w800h450.jpg"
    },
    {
      "title": "Australia Post’s plea to pet owners as dog attacks reach alarming numbers",
      "link": "https://7news.com.au/news/australia-posts-plea-to-pet-owners-as-dog-attacks-reach-alarming-numbers-c-22437383",
      "pubDate": "2026-06-16 04:07:19",
      "excerpt": "‘What seems like a routine delivery can quickly escalate ...’",
      "image": ""
    },
    {
      "title": "Australia's richest woman in $1.4bn deal with Elon Musk",
      "link": "https://7news.com.au/news/australias-richest-woman-in-14bn-deal-with-elon-musk-c-22437621",
      "pubDate": "2026-06-16 03:02:24",
      "excerpt": "‘Elon has done what very few people in history have done.’",
      "image": "https://images.7news.com.au/publication/C-22437621/358a90cf3c6262af9bf4ba92cd890c6b5b99df4a-16x9-x0y0w1280h720.png"
    },
    {
      "title": "Labor admits it hasn’t convinced Australians its tax reforms will leave them better off",
      "link": "https://7news.com.au/sunrise/labor-admits-it-hasnt-convinced-australians-its-tax-reforms-will-leave-them-better-off-c-22436785",
      "pubDate": "2026-06-16 01:12:41",
      "excerpt": "‘Tax reform is hard, we have to keep explaining it.’",
      "image": ""
    },
    {
      "title": "Newsagency addresses ‘$100 million secret’ as massive Powerball prize remains unclaimed",
      "link": "https://7news.com.au/news/newsagency-addresses-100-million-secret-as-massive-powerball-prize-remains-unclaimed-c-22432662",
      "pubDate": "2026-06-16 00:02:36",
      "excerpt": "The winning ticket was purchased more than a year ago.",
      "image": ""
    },
    {
      "title": "Expert warns fuel disruptions could continue after US and Iran sign peace deal",
      "link": "https://7news.com.au/sunrise/expert-warns-elevated-fuel-prices-could-continue-after-us-and-iran-sign-peace-deal-c-22436714",
      "pubDate": "2026-06-15 22:32:37",
      "excerpt": "The Strait of Hormuz reopening presents a new challenge.",
      "image": ""
    },
    {
      "title": "Mother loses arm after being attacked by shark at Sydney’s Coogee Beach",
      "link": "https://7news.com.au/news/shark-bite-victim-identified-after-attack-at-sydneys-coogee-beach-c-22432832",
      "pubDate": "2026-06-15 03:14:07",
      "excerpt": "The 35-year-old mother was attacked on Saturday afternoon.",
      "image": ""
    },
    {
      "title": "Aussies warned over major risks of uploading personal documents to AI platforms",
      "link": "https://7news.com.au/sunrise/aussies-warned-over-major-risks-of-uploading-personal-documents-to-ai-platforms-c-22431899",
      "pubDate": "2026-06-15 02:51:01",
      "excerpt": "‘They don’t have an obligation to give you the best advice...’",
      "image": ""
    }
  ]
}
